defaults: &defaults
  docker:
    - image: cimg/python:3.10.4


version: 2.1

commands: 
  print_pipeline_id:
    description: "Command that prints pipeline id from the env"
    parameters:
      to: 
        type: string
        default: "This is pipeline ID << pipeline.id >>"
    steps:
      - run: echo << parameters.to >>

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, "
  
  print-world:

    docker:
      - image: cimg/python:3.10.4
    
    steps:
      - checkout
      - run:
          name: "say $YUSUF_VAR "
          command: "echo World!"
  
  save_hello_world_output:

    docker:
      - image: cimg/python:3.10.4
    
    steps:
      - checkout
      - run: mkdir -p tmp
      - run:
          name: "VAR "
          command: echo " Hello World!" > tmp/output.txt
      

      - persist_to_workspace:
          root: tmp
          paths: 
            - output.txt

  print_output_file:
    docker:
      - image: cimg/python:3.10.4

    steps:
      - checkout
      - attach_workspace:
          at: /tmp/output.txt
      - run:
          echo "$output.txt"

  print_pipeline_id_from_command:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          - print_pipeline_id:

  

workflows:
  say-hello-workflow:
    jobs:
      
      - say-hello
      - print-world:
          requires:
            - say-hello
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - print_pipeline_id_from_command